---
name: lint

on:
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - lint
          - gen

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "make ${{ matrix.target }}"
        run: |
          retry() {
            for n in $(seq ${RETRIES}); do
              echo "[${n}/${RETRIES}] ${*}";
              if eval "${*}"; then
                echo "[SUCC] ${n}/${RETRIES}";
                return 0;
              fi;
              sleep 2;
              echo "[FAIL] ${n}/${RETRIES}";
            done;
            return 1;
          }

          retry make "${TARGET}"
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }
        env:
          TARGET: ${{ matrix.target }}
          RETRIES: 20
